# Generated by Django 5.1.5 on 2025-02-04 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_in_stock', models.IntegerField()),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_quantity', models.IntegerField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_levels', models.TextField(blank=True, null=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('packaging_info', models.TextField(blank=True, null=True)),
                ('margin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('production_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('classification_code', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_location', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_location', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_info', models.TextField(blank=True, null=True)),
                ('reorder_quantity', models.IntegerField(blank=True, null=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier')),
            ],
        ),
    ]
